config/routes.rb
Rails.application.routes.draw do
  get "/", :controller => "places", :action => "index"
  get '/sessions/:id', to: 'sessions#show', as: 'session'
  resources "places"
  resources "posts"
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources "users"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/place.rb
class Place < ApplicationRecord
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :posts
  has_many :places
  
  validates :username, presence: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_current_user

  private

  def set_current_user
    if session[:user_id]
      @current_user = User.find_by(id: session[:user_id])
    end
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :require_login

  def index
    @places = @current_user.places
  end  

  def show
    @place = Place.find_by({ "id" => params["id"] })
    @posts = Post.where({ "place_id" => @place["id"], "user_id" => @current_user.id })
  end

  def new
    @place = Place.new
  end

  def create
    @place = @current_user.places.new(place_params)
    if @place.save
      redirect_to "/places"
    else
      render :new
    end
  end
  
  private
  
  def place_params
    params.require(:place).permit(:name)
  end
  
  def require_login
    unless @current_user
      redirect_to login_path
    end  
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_login

  def index
    @posts = @current_user.posts
  end
  
  def new
    @post = Post.new
    @post.place_id = params["place_id"]
  end

  def create
    @post = @current_user.posts.new(post_params.except(:image))
    if @post.save
      @post.image.attach(post_params[:image]) if post_params[:image]
      redirect_to "/places/#{@post.place_id}"
    else
      render :new
    end
  end

  private
  
  def post_params
    params.require(:post).permit(:title, :description, :posted_on, :image, :place_id)
  end

  def require_login
    unless @current_user
      redirect_to new_session_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @session = User.new
  end

  def show
    redirect_to login_path
  end

  def create
    @user = User.find_by(email: params[:session][:email].downcase)
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      flash[:success] = "You have successfully logged in"
      redirect_to places_path
    else
      flash.now[:danger] = "There was something wrong with your login information"
      render 'new'
    end
  end
  


  def destroy
    session.delete(:user_id)
    redirect_to login_url
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to places_path, notice: 'User was successfully created. Please sign in.'
    else
      render :new
    end
    
  end
    
  private
  
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <title>Tacostagram Final</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="/stylesheets/application.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="/places">Home</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <% if @current_user %>
            <li class="nav-item">
              <strong style="color: green;">Welcome, <%= @current_user.username %></strong>
            </li>
            <li class="nav-item">
              <%= form_tag logout_path, method: :delete, class: 'nav-link' do %>
                <%= submit_tag 'Logout', class: 'btn btn-link', style: 'padding: 0; text-decoration: none;' %>
              <% end %>
            </li>
          <% else %>
            <li class="nav-item">
              <a class="nav-link" href="/users/new">Signup</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/sessions/new">Login</a>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>

    <div class="container">
      <%= flash["notice"] %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/places/index.html.erb
<div class="row">
  <% @places.each do |place| %>
    <div class="col-sm-4">
      <div class="card mb-4 shadow-sm">
        <div class="card-body">
          <h5 class="card-title"><%= place["name"] %></h5>
          <%= link_to 'Show', place, class: 'btn btn-primary' %>
        </div>
      </div>
    </div>
  <% end %>
</div>
<p>
  <a href="/places/new">New place</a>
</p>

app/views/places/new.html.erb
<h1>New Place</h1>

<%= form_with :model => @place do |form| %>
  <p>
    <%= form.label "name" %>
    <%= form.text_field "name" %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/places/show.html.erb
<h1><%= @place["name"] %></h1>
<h2>My Posts</h2>

<div class="container">
  <div class="row">
    <% @posts.each do |post| %>
      <div class="col-4">
        <div class="card mb-4 shadow-sm">
          <img class="card-img-top" src="<%= post.image.attached? ? url_for(post.image) : "No Picture" %>" alt="Card image cap">
          <div class="card-body">
            <h5 class="card-title"><%= post["title"] %></h5>
            <h6><%= post["posted_on"] %></h6>
            <p class="card-text"><%= post["description"] %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

<p>
 <a href="/posts/new?place_id=<%= @place["id"] %>">New Post</a>
</p>
<p>
 <a href="/places">Back to All Places</a>
</p>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= form_with model: @post do |form| %>
  <%= form.hidden_field "place_id" %>
  <p>
    <%= form.label "title" %>
    <%= form.text_field "title" %>
  </p>
  <p>
    <%= form.label "description" %>
    <%= form.text_field "description" %>
  </p>
  <p>
    <%= form.label "posted_on" %>
    <%= form.date_field "posted_on" %>
  </p>
  <p>
    <%= form.label :image, "Image (Optional)" %>
    <%= form.file_field :image %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_with model: @user, url: users_path, class: 'form-signup' do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.submit 'Sign up', class: 'btn btn-lg btn-primary btn-block' %>
<% end %>